### ISSUE TITLE
How to download only particular threads from subreddit?

### ISSUE THREAD

**Issue by katiefraser** [pistocop/subreddit-comments-dl#3]
Thank you for the very useful code!

Not an issue per se, but a question: If I want to download only specific threads from a subreddit, do you have any suggestions for the best way to do it?

Thanks :)

**Comment by pistocop** [comment]
Hi @katiefraser, I’m glad if the code can be useful!

I think for your case the code you should consider is [this function](https://github.com/pistocop/subreddit-comments-dl/blob/30119183e6a3789f8cef191032f874c43b099e7c/src/subreddit_downloader.py#L162), that take a _submission_ (`sub` parameter) and download all the comments from it.

For a simpler version of a function with similar functionality, I suggest you take a look also on [this page](https://praw.readthedocs.io/en/latest/tutorials/comments.html) at the official praw documentation.

**Comment by katiefraser** [comment]
Thank you, I will check that out!
