### ISSUE TITLE
how to know utc_date

### ISSUE THREAD

**Issue by BogyeomKim** [pistocop/subreddit-comments-dl#4]
Dear pistocop

Hi, this is Bogyeom Kim. First of all, thanks for your code. It help our project a lot. 
While I use, I just wonder how to know utc date which is input for argument of subreddit_downloader.py.
For example, you showed that in order to  download the News comments after 1 January 2021, you used --utc-after 1609459201. 
It would be a great help if you let me know how to turn ordinary data into utc date form. 

Thank you.

Best regards, 
Bogyeom Kim

**Comment by pistocop** [comment]
Hi @BogyeomKim,
I'm glad the repo is useful to you!

You are right, I haven't included on the README any utility to convert the date to UTC timestamp.
I had written an article where I specify more deeply the software usages:
[https://towardsdatascience.com/how-download-subreddit-comments-f79557c99170](https://towardsdatascience.com/how-download-subreddit-comments-f79557c99170)

Related to your case, to convert the date you could use this website:
[https://www.epochconverter.com/](https://www.epochconverter.com/)

Anyway it shouldn't be difficult to integrate a converter to make easier the package usage. 
Actually, I haven't planned to make that change but I will open an issue to track the change.

Regards,
Simone
