### ISSUE TITLE
scraping all the comments in order

### ISSUE THREAD

**Issue by naveen-malla** [pistocop/subreddit-comments-dl#7]
Does this program scrape comments of a given post in the order of their occurrence without messing with the hierarchy? The praw library helps in scraping all the comments but they are not in order. Please let me know if this program can do that and the command I should use.

**Comment by pistocop** [comment]
Hi @naveenmalla046, 
actually, no the software doesn't support your user case.

But I think you could implement it, the subreddit downloader already keep track of the comments creation time:

https://github.com/pistocop/subreddit-comments-dl/blob/a9f02a0a041be3b1f425b4cce1e57e658a737754/src/subreddit_downloader.py#L181

So you could manage this information the [database_builder.py](https://github.com/pistocop/subreddit-comments-dl/blob/master/src/dataset_builder.py) script, the bigger challenge is that the comments are stored on multiple files:

https://github.com/pistocop/subreddit-comments-dl/blob/a9f02a0a041be3b1f425b4cce1e57e658a737754/src/dataset_builder.py#L155

Let me know if you find a solution!
Regards,
Simone
